language: objective-c
osx_image: xcode11.3

env:
  global:
  - NODE_VERSION=stable

install:
- brew tap wix/brew
- brew install applesimutils
- curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
- export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
- nvm install $NODE_VERSION
- nvm use $NODE_VERSION
- nvm alias default $NODE_VERSION

- npm install -g react-native-cli
- npm install -g detox-cli
- npm install -g expo-cli
- npm install detox

before_script:
- ./setup.sh

script:
- echo 'Starting expo in separate process'
- expo start --ios &
- echo 'Waiting on expo to start in other process and open an ios sim'
- sleep 60
- echo 'Running detox tests'
- detox test --configuration ios.sim --cleanup
